### ISSUE TITLE
Замінити API лінк на сервіс тривог

### ISSUE THREAD

**Issue by Vadimkin** [benms/ua-alerts-map#1]
Привіт!

Якщо все ще використовуєте API повітряних тривог, то замініть, будь ласка, `https://emapa.fra1.cdn.digitaloceanspaces.com/statuses.json` → `https://vadimklimenko.com/map/statuses.json`, там повністю відповідь 1-в-1. Приблизно через тиждень я перестану оновлювати файл на DO Spaces (перший лінк).

Дякую!

https://github.com/benms/ua-alerts-map/blob/58c3371e9a28f916a950f58e5385334e8a0a1553/download_regions.py#L42-L45

**Comment by benms** [comment]
Привіт @Vadimkin , виправив. Дякую!
